name: 🐞 Bug Report
description: Open a new issue for a bug that has not yet been reported
title: "[UserScriptName] bugName"
labels: ["bug"]
body:
  - type: input
    id: userscriptName
    validations:
      required: true
    attributes:
      label: 🐵 UserScript
      description: What is the name and version of the UserScript you are reporting a bug for?
      placeholder: FilmFancy [v2.5]
  - type: textarea
    id: bugDescription
    validations:
      required: true
    attributes:
      label: ✏️ Description
      description: Briefly explain the expected behaviour, the buggy behaviour, and how this bug can be reproduced.
  - type: input
    id: userBrowser
    validations:
      required: true
    attributes:
      label: 🖥️ Browser
      description: On what browser are you encountering this bug?
      placeholder: LibreWolf
  - type: dropdown
    id: userscriptManager
    validations:
      required: true
    attributes:
      label: 🐵 UserScript Manager
      description: What UserScript manager are you using?
      multiple: true
      default: 0
      options:
        - Violentmonkey
        - Tampermonkey
        - Greasemonkey
        - Other
  - type: textarea
    id: consoleMessages
    validations:
      required: true
    attributes:
      label: 📄 Console Messages
      description: Copy-paste the browser console log\error messages related to this bug. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: userConfirmation
    attributes:
      label: Confirm New Issue
      description: By creating this issue, you agree that you have searched and confirmed that this bug has not alrady been reported and it is not a result form conflicting with another UserScripts\programs
      options:
        - label: Yes, I have searched for and confirmed this bug has not yet been reported
          required: true
        - label: Yes, I can reproduce this bug even after disabling other UserScripts\program that may cause interference
          required: true

