name: 🐞 Bug Report
description: Create a new issue for a bug that has not yet been reported
title: "[UserScriptName] bugName"
labels: ["bug"]
body:
  - type: input
    id: userscriptName
    validations:
      required: true
    attributes:
      label: 🐵 UserScript
      description: What is the name and version of the UserScript you are reporting a bug for?
      placeholder: FilmFancy, v2.5
  - type: textarea
    id: bugDescription
    validations:
      required: true
    attributes:
      label: ✏️ Description
      description: Briefly explain the expected behaviour, the buggy behaviour, and how this bug can be reproduced.
  - type: input
    id: userBrowser
    validations:
      required: true
    attributes:
      label: 🖥️ Browser
      description: What browsers are you seeing the problem on?
      placeholder: LibreWolf
  - type: dropdown
    id: userscriptManager
    validations:
      required: true
    attributes:
      label: 🐵 UserScript Manager
      description: What UserScript manager are you using?
      multiple: true
      default: 0
      options:
        - Violentmonkey
        - Tampermonkey
        - Greasemonkey
        - Other
  - type: textarea
    id: consoleMessages
    validations:
      required: true
    attributes:
      label: 📄 Console Messages
      description: Paste the browser console logs errors related to this bug. This will be automatically formatted into code, so no need for backticks.
      render: shell

